# Generated by Django 5.1.4 on 2026-05-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('FIRMAR', 'Firma digital'), ('COMPLETAR', 'Completar'), ('DISPENSAR', 'Dispensar'), ('ANULAR', 'Anular')], db_index=True, max_length=20)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.CharField(db_index=True, max_length=50)),
                ('objeto_repr', models.CharField(blank=True, max_length=200)),
                ('usuario_id', models.IntegerField(db_index=True)),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('usuario_rol', models.CharField(max_length=50)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tenant_nombre', models.CharField(blank=True, max_length=200)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('hash_evento', models.CharField(blank=True, db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='Auditoria_r_modelo_60cd0a_idx'), models.Index(fields=['usuario_id', 'timestamp'], name='Auditoria_r_usuario_7accdc_idx'), models.Index(fields=['accion', 'timestamp'], name='Auditoria_r_accion_2d4247_idx')],
            },
        ),
    ]
