<<<<<<< HEAD
# Generated by Django 5.1.4 on 2026-05-18 00:26
=======
# Generated by Django 5.1.4 on 2026-05-11 02:31
>>>>>>> 1a6b77f1ffa3186e1c6bfe4624c64cdc6912d072

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('FIRMAR', 'Firma digital'), ('COMPLETAR', 'Completar'), ('DISPENSAR', 'Dispensar'), ('ANULAR', 'Anular'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión')], db_index=True, max_length=20),
        ),
    ]
