# Generated by Django 5.1.4 on 2026-04-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial del establecimiento de salud. Ej: Hospital San Juan de Dios', max_length=200, verbose_name='Nombre del establecimiento')),
                ('slug', models.SlugField(help_text='Identificador URL-friendly del establecimiento. Ej: hospital-san-juan. Se usa internamente.', max_length=100, unique=True, verbose_name='Identificador único')),
                ('nit', models.CharField(blank=True, default='', help_text='Número de Identificación Tributaria del establecimiento.', max_length=20, verbose_name='NIT')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar para suspender acceso al establecimiento sin eliminar sus datos.', verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['nombre'],
            },
        ),
    ]
