# Generated by Django 5.1.4 on 2026-05-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contacto', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contacto')),
                ('sitio_web', models.CharField(blank=True, default='', max_length=200, verbose_name='Sitio web')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=5, verbose_name='Idioma')),
                ('moneda', models.CharField(default='BOB', help_text='Código ISO 4217. Ej: BOB, USD, PEN, ARS.', max_length=10, verbose_name='Moneda')),
                ('zona_horaria', models.CharField(default='America/La_Paz', max_length=60, verbose_name='Zona horaria')),
                ('modulos_habilitados', models.JSONField(default=list, help_text="Lista de códigos de módulo activos (ej: ['CU7','CU8']). Lista vacía = todos los módulos habilitados.", verbose_name='Módulos habilitados')),
                ('campos_extra_paciente', models.JSONField(default=list, help_text='Lista de objetos {nombre, etiqueta, tipo, requerido} para campos adicionales en el formulario de paciente.', verbose_name='Campos extra en Paciente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='Tenants.tenant', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Configuración de establecimiento',
                'verbose_name_plural': 'Configuraciones de establecimientos',
            },
        ),
    ]
