# Generated by Django 5.1.4 on 2026-04-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConsultaMedicaSOAP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudio', models.CharField(choices=[('LAB', 'Laboratorio'), ('RX', 'Radiografía'), ('ECO', 'Ecografía'), ('TAC', 'Tomografía'), ('RMN', 'Resonancia Magnética'), ('ECG', 'Electrocardiograma'), ('END', 'Endoscopía'), ('BIO', 'Biopsia'), ('OTR', 'Otro')], db_index=True, max_length=5)),
                ('descripcion_estudio', models.CharField(max_length=300)),
                ('indicacion_clinica', models.TextField()),
                ('observaciones', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=15)),
                ('urgente', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='ConsultaMedicaSOAP.consulta')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Estudio',
                'verbose_name_plural': 'Órdenes de Estudio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resultado', models.DateTimeField()),
                ('archivo_adjunto', models.CharField(blank=True, default='', max_length=512)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('valores_resultado', models.TextField(blank=True, default='')),
                ('interpretacion_medica', models.TextField(blank=True, default='')),
                ('fecha_interpretacion', models.DateTimeField(blank=True, null=True)),
                ('hash_archivo', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ingresado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_ingresados', to=settings.AUTH_USER_MODEL)),
                ('interpretado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_interpretados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='SolicitudDeEstudios.ordenestudio')),
            ],
            options={
                'verbose_name': 'Resultado de Estudio',
                'verbose_name_plural': 'Resultados de Estudios',
            },
        ),
        migrations.AddIndex(
            model_name='ordenestudio',
            index=models.Index(fields=['estado', 'urgente'], name='idx_orden_estado_urgente'),
        ),
    ]
