# Generated by Django 5.1.4 on 2026-04-04 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConsultaMedicaSOAP', '0001_initial'),
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagen'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('indicaciones', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, default='')),
                ('archivo_resultado', models.CharField(blank=True, default='', max_length=500)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='ConsultaMedicaSOAP.consultasoap')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='RegistroYBusquedaDePacientes.paciente')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Estudio',
                'verbose_name_plural': 'Solicitudes de Estudios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
