# Generated by Django 5.1.4 on 2026-04-05 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaMedicaSOAP', '0002_alter_consulta_actualizado_en_and_more'),
        ('SolicitudDeEstudios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestudio',
            name='consulta',
            field=models.ForeignKey(help_text='Consulta médica en la que se solicitó este estudio.', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='ConsultaMedicaSOAP.consulta', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='descripcion_estudio',
            field=models.CharField(help_text='Nombre específico del estudio. Ej: Hemograma completo, Rx tórax PA, Ecografía abdominal.', max_length=300, verbose_name='Descripción del estudio'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', help_text='Flujo: PENDIENTE → EN_PROCESO → DISPONIBLE → ENTREGADO. O CANCELADO si no se realiza.', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text='Fecha máxima para que el resultado esté disponible. Opcional.', null=True, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de cuándo se realizó la orden.', verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='indicacion_clinica',
            field=models.TextField(help_text='Justificación clínica del estudio. Obligatorio para el laboratorio/imagen. Ej: Sospecha de neumonía.', verbose_name='Indicación clínica'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='medico_solicitante',
            field=models.ForeignKey(help_text='Médico que solicitó el estudio.', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico solicitante'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Instrucciones especiales para el técnico. Ej: paciente en ayunas, preparación especial.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='tipo_estudio',
            field=models.CharField(choices=[('LAB', 'Laboratorio'), ('RX', 'Radiografía'), ('ECO', 'Ecografía'), ('TAC', 'Tomografía'), ('RMN', 'Resonancia Magnética'), ('ECG', 'Electrocardiograma'), ('END', 'Endoscopía'), ('BIO', 'Biopsia'), ('OTR', 'Otro')], db_index=True, help_text='Categoría del estudio: LAB=Laboratorio, RX=Radiografía, ECO=Ecografía, TAC, RMN, etc.', max_length=5, verbose_name='Tipo de estudio'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='urgente',
            field=models.BooleanField(default=False, help_text='True = resultado necesario el mismo día. Activa cola prioritaria en laboratorio.', verbose_name='Urgente'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='archivo_adjunto',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa del archivo en el servidor o clave en S3/MinIO. Ej: resultados/2026/hemograma_42.pdf.', max_length=512, verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de cuándo se cargó el resultado.', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='fecha_interpretacion',
            field=models.DateTimeField(blank=True, help_text='Cuándo interpretó el médico el resultado.', null=True, verbose_name='Fecha de interpretación'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='fecha_resultado',
            field=models.DateTimeField(help_text='Cuándo estuvo listo el resultado del estudio.', verbose_name='Fecha del resultado'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='hash_archivo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 del archivo adjunto. Se ancla en blockchain para verificación de integridad forense.', max_length=64, verbose_name='Hash del archivo'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='ingresado_por',
            field=models.ForeignKey(help_text='Laboratorista o técnico que cargó el resultado al sistema.', on_delete=django.db.models.deletion.PROTECT, related_name='resultados_ingresados', to=settings.AUTH_USER_MODEL, verbose_name='Ingresado por'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='interpretacion_medica',
            field=models.TextField(blank=True, default='', help_text='Interpretación del médico tratante al revisar el resultado. Se llena después de la entrega.', verbose_name='Interpretación médica'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='interpretado_por',
            field=models.ForeignKey(blank=True, help_text='Médico que interpretó el resultado. Nulo hasta que el médico lo revise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_interpretados', to=settings.AUTH_USER_MODEL, verbose_name='Interpretado por'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', help_text='Nombre original del archivo para mostrar al usuario. Ej: Hemograma_Juan_Perez.pdf.', max_length=255, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='orden',
            field=models.OneToOneField(help_text='Orden de estudio a la que corresponde este resultado.', on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='SolicitudDeEstudios.ordenestudio', verbose_name='Orden de estudio'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='valores_resultado',
            field=models.TextField(blank=True, default='', help_text='Valores en texto libre para resultados de laboratorio. Ej: Hemoglobina: 12.5 g/dL, Hematocrito: 38%.', verbose_name='Valores del resultado'),
        ),
    ]
