# Generated by Django 5.1.4 on 2026-05-03 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaMedicaSOAP', '0005_remove_consulta_paciente_ficha_not_null'),
        ('SolicitudDeEstudios', '0003_t009_orden_estudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenestudio',
            options={'ordering': ['-urgente', '-fecha_solicitud'], 'verbose_name': 'Orden de Estudio', 'verbose_name_plural': 'Órdenes de Estudio'},
        ),
        migrations.RenameIndex(
            model_name='ordenestudio',
            new_name='SolicitudDe_estado_b95307_idx',
            old_name='orden_est_ix_est_urg',
        ),
        migrations.RenameIndex(
            model_name='ordenestudio',
            new_name='SolicitudDe_consult_36cc07_idx',
            old_name='orden_est_ix_cons_est',
        ),
        migrations.RenameIndex(
            model_name='ordenestudio',
            new_name='SolicitudDe_fecha_s_0f42a9_idx',
            old_name='orden_est_ix_fecha_sol',
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_estudio', to='ConsultaMedicaSOAP.consulta', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='indicacion_clinica',
            field=models.TextField(help_text='Justificación médica del estudio.', verbose_name='Indicación clínica'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='tipo',
            field=models.CharField(choices=[('LAB', 'Laboratorio'), ('RX', 'Radiografía'), ('ECO', 'Ecografía'), ('TC', 'Tomografía Computarizada'), ('RMN', 'Resonancia Magnética'), ('ECG', 'Electrocardiograma'), ('END', 'Endoscopía'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='archivo_adjunto',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='fecha_interpretacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de interpretación'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='fecha_resultado',
            field=models.DateTimeField(verbose_name='Fecha del resultado'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='hash_archivo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Hash del archivo'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='ingresado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_ingresados', to=settings.AUTH_USER_MODEL, verbose_name='Ingresado por'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='interpretacion_medica',
            field=models.TextField(blank=True, default='', verbose_name='Interpretación médica'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='interpretado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_interpretados', to=settings.AUTH_USER_MODEL, verbose_name='Interpretado por'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='SolicitudDeEstudios.ordenestudio', verbose_name='Orden de estudio'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='valores_resultado',
            field=models.TextField(blank=True, default='', verbose_name='Valores del resultado'),
        ),
    ]
