# Generated by Django 5.1.4 on 2026-06-19 16:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tenants', '0002_configuraciontenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('BASICO', 'Básico'), ('PROFESIONAL', 'Profesional'), ('ENTERPRISE', 'Enterprise')], default='BASICO', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PENDIENTE', 'Pendiente de pago'), ('EXPIRADA', 'Expirada'), ('SUSPENDIDA', 'Suspendida')], default='PENDIENTE', max_length=20)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_ultimo_pago', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='Tenants.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['tenant__nombre'],
            },
        ),
    ]
