# Generated by Django 5.1.4 on 2026-05-06 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username en el momento de la acción, guardado por si el usuario se elimina.', max_length=150, verbose_name='Username')),
                ('metodo', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, verbose_name='Método HTTP')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Ruta')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Código de respuesta')),
                ('duracion_ms', models.FloatField(verbose_name='Duración (ms)')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='Body del request')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['username', 'creado_en'], name='idx_auditoria_user_fecha'), models.Index(fields=['metodo', 'creado_en'], name='idx_auditoria_metodo_fecha')],
            },
        ),
    ]
