# Generated by Django 5.1.4 on 2026-05-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0005_merge_20260424_0726'),
        ('Tenants', '0002_configuraciontenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConsentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción (Texto legal)')),
                ('requiere_testigo', models.BooleanField(default=False, verbose_name='Requiere testigo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_consentimiento', to='Tenants.tenant', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Consentimiento',
                'verbose_name_plural': 'Tipos de Consentimiento',
                'ordering': ['nombre'],
                'unique_together': {('tenant', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OTORGADO', 'Otorgado'), ('RECHAZADO', 'Rechazado'), ('REVOCADO', 'Revocado')], default='OTORGADO', max_length=20, verbose_name='Estado')),
                ('otorgado_en', models.DateTimeField(auto_now_add=True, verbose_name='Otorgado en')),
                ('vigente_hasta', models.DateTimeField(blank=True, help_text='Fecha de expiración. Dejar en blanco para vigencia indefinida.', null=True, verbose_name='Vigente hasta')),
                ('testigo_nombre', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del testigo')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='RegistroYBusquedaDePacientes.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='Tenants.tenant', verbose_name='Establecimiento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='ConfiguracionDeConsentimiento.tipoconsentimiento', verbose_name='Tipo de consentimiento')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-otorgado_en'],
                'indexes': [models.Index(fields=['paciente', 'tipo', 'estado'], name='Configuraci_pacient_1afe97_idx'), models.Index(fields=['otorgado_en'], name='Configuraci_otorgad_5e1b22_idx')],
            },
        ),
    ]
