# Generated by Django 5.1.4 on 2026-06-21 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0005_merge_20260424_0726'),
        ('Tenants', '0002_configuraciontenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgamiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de otorgamiento')),
                ('fecha_revocacion', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de revocación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('otorgado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_otorgados', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='RegistroYBusquedaDePacientes.paciente', verbose_name='Paciente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_paciente', to='Tenants.tenant', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Permiso de Paciente',
                'verbose_name_plural': 'Permisos de Pacientes',
                'ordering': ['-fecha_otorgamiento'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('paciente', 'medico'), name='unique_active_permiso_paciente_medico')],
            },
        ),
    ]
