# Generated by Django 5.1.4 on 2026-05-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AperturaFichaYColaDeAtencion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ficha',
            new_name='AperturaFic_estado_c1cc19_idx',
            old_name='ficha_ix_est_ap',
        ),
        migrations.RenameIndex(
            model_name='ficha',
            new_name='AperturaFic_pacient_a51e38_idx',
            old_name='ficha_ix_pac_est',
        ),
    ]
