# Generated by Django 5.1.4 on 2026-05-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AperturaFichaYColaDeAtencion', '0002_rename_ficha_ix_est_ap_aperturafic_estado_c1cc19_idx_and_more'),
        ('AperturaFichaYColaDeAtencion', '0002_tipoatencion'),
    ]

    operations = [
    ]
