# Generated by Django 5.1.4 on 2026-04-04 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('sintomas', models.TextField(blank=True, default='')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('glasgow', models.IntegerField(blank=True, null=True)),
                ('dolor_eva', models.IntegerField(blank=True, null=True)),
                ('prioridad', models.IntegerField(choices=[(1, 'Rojo - Inmediato'), (2, 'Naranja - Muy urgente'), (3, 'Amarillo - Urgente'), (4, 'Verde - Poco urgente'), (5, 'Azul - No urgente')], default=3)),
                ('clasificacion_ia', models.CharField(blank=True, default='', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triajes_registrados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='RegistroYBusquedaDePacientes.paciente')),
            ],
            options={
                'verbose_name': 'Triaje',
                'verbose_name_plural': 'Triajes',
                'ordering': ['-fecha'],
            },
        ),
    ]
