# Generated by Django 5.1.4 on 2026-04-05 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(500)])),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)])),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(80)])),
                ('presion_sistolica', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('presion_diastolica', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('temperatura_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(45)])),
                ('saturacion_oxigeno', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('glucemia', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('escala_dolor', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nivel_urgencia', models.CharField(blank=True, choices=[('ROJO', 'Rojo - Inmediato'), ('NARANJA', 'Naranja - Muy urgente'), ('AMARILLO', 'Amarillo - Urgente'), ('VERDE', 'Verde - Poco urgente'), ('AZUL', 'Azul - No urgente')], db_index=True, max_length=10, null=True)),
                ('motivo_consulta_triaje', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('hora_triaje', models.DateTimeField(auto_now_add=True)),
                ('enfermera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triajes_registrados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='RegistroYBusquedaDePacientes.paciente')),
            ],
            options={
                'verbose_name': 'Triaje',
                'verbose_name_plural': 'Triajes',
                'ordering': ['-hora_triaje'],
                'constraints': [models.CheckConstraint(condition=models.Q(('peso_kg__gte', 0.5), ('peso_kg__lte', 500)), name='triaje_peso_rango'), models.CheckConstraint(condition=models.Q(('talla_cm__gte', 20), ('talla_cm__lte', 250)), name='triaje_talla_rango'), models.CheckConstraint(condition=models.Q(('frecuencia_cardiaca__gte', 20), ('frecuencia_cardiaca__lte', 300)), name='triaje_fc_rango'), models.CheckConstraint(condition=models.Q(('frecuencia_respiratoria__gte', 5), ('frecuencia_respiratoria__lte', 80)), name='triaje_fr_rango'), models.CheckConstraint(condition=models.Q(('presion_sistolica__gte', 40), ('presion_sistolica__lte', 300)), name='triaje_ps_rango'), models.CheckConstraint(condition=models.Q(('presion_diastolica__gte', 20), ('presion_diastolica__lte', 200)), name='triaje_pd_rango'), models.CheckConstraint(condition=models.Q(('temperatura_celsius__gte', 25), ('temperatura_celsius__lte', 45)), name='triaje_temp_rango'), models.CheckConstraint(condition=models.Q(('saturacion_oxigeno__gte', 50), ('saturacion_oxigeno__lte', 100)), name='triaje_spo2_rango'), models.CheckConstraint(condition=models.Q(('escala_dolor__gte', 0), ('escala_dolor__lte', 10)), name='triaje_dolor_rango')],
            },
        ),
    ]
