# Generated by Django 5.1.4 on 2026-04-05 00:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeTriaje', '0001_initial'),
        ('RegistroYBusquedaDePacientes', '0002_alter_paciente_activo_alter_paciente_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='enfermera',
            field=models.ForeignKey(help_text='Personal de enfermería que realizó el triaje.', on_delete=django.db.models.deletion.PROTECT, related_name='triajes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Enfermera/o'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='escala_dolor',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Escala Visual Analógica: 0 = sin dolor, 10 = dolor máximo insoportable.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Escala de dolor EVA'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='frecuencia_cardiaca',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Latidos por minuto. Rango válido: 20 – 300 lpm.', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Frecuencia cardíaca (lpm)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='frecuencia_respiratoria',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Respiraciones por minuto. Rango válido: 5 – 80 rpm.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(80)], verbose_name='Frecuencia respiratoria (rpm)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='glucemia',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Glucosa en sangre capilar en mg/dL. Solo si aplica clínicamente.', max_digits=6, null=True, verbose_name='Glucemia capilar (mg/dL)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='hora_triaje',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de cuándo se realizó el triaje.', verbose_name='Hora de triaje'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='motivo_consulta_triaje',
            field=models.TextField(blank=True, default='', help_text='Resumen del motivo de consulta anotado por enfermería. Este texto es procesado por el modelo NLP de triaje.', verbose_name='Motivo de consulta (triaje)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='nivel_urgencia',
            field=models.CharField(blank=True, choices=[('ROJO', 'Rojo - Inmediato'), ('NARANJA', 'Naranja - Muy urgente'), ('AMARILLO', 'Amarillo - Urgente'), ('VERDE', 'Verde - Poco urgente'), ('AZUL', 'Azul - No urgente')], db_index=True, help_text='Clasificación de urgencia. Puede ser asignada por el modelo IA o manualmente por enfermería.', max_length=10, null=True, verbose_name='Nivel de urgencia'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Observaciones adicionales de enfermería durante el triaje.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente al que se le realizó el triaje.', on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='RegistroYBusquedaDePacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso del paciente en kilogramos. Rango válido: 0.5 – 500 kg.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(500)], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='presion_diastolica',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de abajo en la presión arterial. Rango válido: 20 – 200 mmHg.', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Presión diastólica (mmHg)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='presion_sistolica',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de arriba en la presión arterial. Rango válido: 40 – 300 mmHg.', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)], verbose_name='Presión sistólica (mmHg)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='saturacion_oxigeno',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Saturación de oxígeno en sangre. Rango válido: 50 – 100 %. Normal > 95%.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Saturación de oxígeno (SpO2 %)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='talla_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Talla del paciente en centímetros. Rango válido: 20 – 250 cm.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='Talla (cm)'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='temperatura_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en grados Celsius. Rango válido: 25 – 45 °C.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(45)], verbose_name='Temperatura (°C)'),
        ),
    ]
