# Generated by Django 5.1.4 on 2026-05-04 00:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeTriaje', '0003_triaje_tenant'),
        ('RegistroYBusquedaDePacientes', '0004_alter_paciente_unique_together_paciente_tenant_and_more'),
        ('Tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triaje',
            name='fue_sobreescrito',
            field=models.BooleanField(default=False, help_text='True si la enfermera cambió el nivel sugerido por la IA.', verbose_name='Sobreescrito por enfermería'),
        ),
        migrations.AddField(
            model_name='triaje',
            name='glasgow',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Escala de coma de Glasgow: 3 (coma profundo) – 15 (normal).', null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)], verbose_name='Escala de Glasgow'),
        ),
        migrations.AddField(
            model_name='triaje',
            name='justificacion_override',
            field=models.TextField(blank=True, default='', help_text='Obligatorio cuando fue_sobreescrito=True. Queda en auditoría.', verbose_name='Justificación del cambio'),
        ),
        migrations.AddField(
            model_name='triaje',
            name='nivel_sugerido_ia',
            field=models.CharField(blank=True, choices=[('ROJO', 'Rojo - Inmediato'), ('NARANJA', 'Naranja - Muy urgente'), ('AMARILLO', 'Amarillo - Urgente'), ('VERDE', 'Verde - Poco urgente'), ('AZUL', 'Azul - No urgente')], help_text='Nivel que el modelo ML sugirió antes de la confirmación de enfermería.', max_length=10, null=True, verbose_name='Nivel sugerido por IA'),
        ),
        migrations.AddField(
            model_name='triaje',
            name='reglas_duras_aplicadas',
            field=models.BooleanField(default=False, help_text='True si el modelo forzó un nivel por SpO₂, PA o Glasgow críticos.', verbose_name='Reglas duras aplicadas'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='nivel_urgencia',
            field=models.CharField(blank=True, choices=[('ROJO', 'Rojo - Inmediato'), ('NARANJA', 'Naranja - Muy urgente'), ('AMARILLO', 'Amarillo - Urgente'), ('VERDE', 'Verde - Poco urgente'), ('AZUL', 'Azul - No urgente')], db_index=True, help_text='Nivel confirmado. Igual al sugerido por IA salvo que enfermería lo haya sobreescrito.', max_length=10, null=True, verbose_name='Nivel de urgencia final'),
        ),
        migrations.AddConstraint(
            model_name='triaje',
            constraint=models.CheckConstraint(condition=models.Q(('glasgow__gte', 3), ('glasgow__lte', 15)), name='triaje_glasgow_rango'),
        ),
    ]
