# Generated by Django 5.1.4 on 2026-05-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeTriaje', '0003_triaje_tenant'),
        ('RegistroDeTriaje', '0004_remove_triaje_paciente_ficha_not_null'),
    ]

    operations = [
    ]
