# Generated by Django 5.1.4 on 2026-05-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeTriaje', '0004_triaje_fue_sobreescrito_triaje_glasgow_and_more'),
        ('RegistroDeTriaje', '0005_merge_20260503_2050'),
    ]

    operations = [
    ]
