# Generated by Django 5.1.4 on 2026-05-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeTriaje', '0006_merge_20260504_2342'),
        ('RegistroDeTriaje', '0006_merge_20260506_1534'),
    ]

    operations = [
    ]
