# Generated by Django 5.1.4 on 2026-04-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(db_index=True, max_length=15, verbose_name='Carnet de Identidad')),
                ('ci_complemento', models.CharField(blank=True, default='', max_length=5, verbose_name='Complemento CI')),
                ('nombres', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('autoidentificacion', models.CharField(choices=[('QUECHUA', 'Quechua'), ('AYMARA', 'Aymara'), ('GUARANI', 'Guaraní'), ('CHIQUITANO', 'Chiquitano'), ('MOJENO', 'Mojeno'), ('MESTIZO', 'Mestizo'), ('BLANCO', 'Blanco'), ('AFRO', 'Afroboliviano'), ('OTRO', 'Otro'), ('NE', 'No Especificado')], default='NE', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('nombre_responsable', models.CharField(blank=True, default='', max_length=200)),
                ('telefono_responsable', models.CharField(blank=True, default='', max_length=20)),
                ('parentesco_responsable', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_seguro', models.CharField(choices=[('SUS', 'SUS'), ('CNS', 'CNS'), ('COSSMIL', 'COSSMIL'), ('BANCARIA', 'Bancaria'), ('PETROLERA', 'Petrolera'), ('PRIVADO', 'Privado'), ('PARTICULAR', 'Particular')], default='PARTICULAR', max_length=20)),
                ('numero_asegurado', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
                'indexes': [models.Index(fields=['ci'], name='idx_paciente_ci'), models.Index(fields=['apellido_paterno', 'apellido_materno'], name='idx_paciente_apellidos')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ci', ''), _negated=True), name='paciente_ci_no_vacio')],
                'unique_together': {('ci', 'ci_complemento')},
            },
        ),
    ]
