# Generated by Django 5.1.4 on 2026-04-05 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True, help_text='False = soft-delete. El registro nunca se borra físicamente de la BD.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación.', verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', help_text='Segundo apellido. Puede estar vacío si el paciente tiene un solo apellido.', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(help_text='Primer apellido del paciente.', max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='autoidentificacion',
            field=models.CharField(choices=[('QUECHUA', 'Quechua'), ('AYMARA', 'Aymara'), ('GUARANI', 'Guaraní'), ('CHIQUITANO', 'Chiquitano'), ('MOJENO', 'Mojeno'), ('MESTIZO', 'Mestizo'), ('BLANCO', 'Blanco'), ('AFRO', 'Afroboliviano'), ('OTRO', 'Otro'), ('NE', 'No Especificado')], default='NE', help_text='Obligatorio por normativa Ministerio de Salud Bolivia. NE = No Especificado.', max_length=20, verbose_name='Autoidentificación étnica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(db_index=True, help_text='Número de CI sin complemento. Ej: 12345678. No puede estar vacío.', max_length=15, verbose_name='Carnet de Identidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci_complemento',
            field=models.CharField(blank=True, default='', help_text='Complemento del CI boliviano. Ej: 1A, 2B. Dejar vacío si no aplica.', max_length=5, verbose_name='Complemento del CI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de cuándo se registró el paciente.', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Personal de salud que registró al paciente en el sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, default='', help_text='Dirección del domicilio del paciente. Opcional.', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Formato YYYY-MM-DD. Se usa para calcular la edad dinámicamente.', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_responsable',
            field=models.CharField(blank=True, default='', help_text='Padre, madre o tutor para menores. Contacto de emergencia para adultos.', max_length=200, verbose_name='Nombre del responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(help_text='Nombres de pila del paciente tal como aparecen en el CI.', max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_asegurado',
            field=models.CharField(blank=True, default='', help_text='Número de afiliación en la caja de salud. Solo si no es PARTICULAR.', max_length=50, verbose_name='Número de asegurado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco_responsable',
            field=models.CharField(blank=True, default='', help_text='Relación con el paciente. Ej: madre, padre, cónyuge, tutor, hijo/a.', max_length=50, verbose_name='Parentesco del responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Sexo biológico del paciente según normativa SNIS Bolivia: M o F.', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Número de teléfono o celular del paciente. Opcional.', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_responsable',
            field=models.CharField(blank=True, default='', help_text='Teléfono del responsable o contacto de emergencia.', max_length=20, verbose_name='Teléfono del responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_seguro',
            field=models.CharField(choices=[('SUS', 'SUS'), ('CNS', 'CNS'), ('COSSMIL', 'COSSMIL'), ('BANCARIA', 'Bancaria'), ('PETROLERA', 'Petrolera'), ('PRIVADO', 'Privado'), ('PARTICULAR', 'Particular')], default='PARTICULAR', help_text='Seguro de salud del paciente. PARTICULAR si no tiene seguro.', max_length=20, verbose_name='Tipo de seguro'),
        ),
    ]
