# Generated by Django 5.1.4 on 2026-04-22 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0003_paciente_email_opcion_sexo_o'),
        ('Tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='Tenants.tenant', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='autoidentificacion',
            field=models.CharField(choices=[('QUECHUA', 'Quechua'), ('AYMARA', 'Aymara'), ('GUARANI', 'Guaraní'), ('CHIQUITANO', 'Chiquitano'), ('MOJENO', 'Mojeno'), ('MESTIZO', 'Mestizo'), ('BLANCO', 'Blanco'), ('AFRO', 'Afroboliviano'), ('OTRO', 'Otro'), ('NE', 'No Especificado')], default='NE', max_length=20, verbose_name='Autoidentificación étnica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Carnet de Identidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci_complemento',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Complemento del CI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, default='', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_responsable',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_asegurado',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número de asegurado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco_responsable',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Parentesco del responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_responsable',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono del responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_seguro',
            field=models.CharField(choices=[('SUS', 'SUS'), ('CNS', 'CNS'), ('COSSMIL', 'COSSMIL'), ('BANCARIA', 'Bancaria'), ('PETROLERA', 'Petrolera'), ('PRIVADO', 'Privado'), ('PARTICULAR', 'Particular')], default='PARTICULAR', max_length=20, verbose_name='Tipo de seguro'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('ci', 'ci_complemento', 'tenant')},
        ),
    ]
