# Generated by Django 5.1.4 on 2026-04-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0004_alter_paciente_activo_alter_paciente_actualizado_en_and_more'),
        ('RegistroYBusquedaDePacientes', '0004_alter_paciente_unique_together_paciente_tenant_and_more'),
    ]

    operations = [
    ]
