"""
Django settings for Histolink project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import Csv, config


def _env_bool(value: str, default: bool = False) -> bool:
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-$g26eq)8pmyp8b_yajdx(c-_cfmahvxa6#%0gcy#!by-=^5^ml",
)

STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool(config("DEBUG", default="True"), default=True)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,10.0.2.2,192.168.0.108",
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # ── Multitenant ───────────────────────────────────────────────────
    "Tenants",
    # ── GestionDeUsuarios ─────────────────────────────────────────────
    "GestionDeUsuarios.LoginYAutenticacion",
    "GestionDeUsuarios.GestionDePersonalDeSalud",
    "GestionDeUsuarios.RegistroYBusquedaDePacientes",
    "GestionDeUsuarios.VisualizacionDelExpediente",
    "GestionDeUsuarios.EdicionDeAntecedentesMedicos",
    # ── AtencionClinica ───────────────────────────────────────────────
    "AtencionClinica.AperturaFichaYColaDeAtencion",
    "AtencionClinica.RegistroDeTriaje",
    "AtencionClinica.ConsultaMedicaSOAP",
    "AtencionClinica.EmisionDeRecetaMedica",
    "AtencionClinica.SolicitudDeEstudios",
    "AtencionClinica.FirmaDigitalDeConsulta",
    # ── IA_Blockchain ─────────────────────────────────────────────────
    "IA_Blockchain.ClasificacionDeUrgenciaConIA",
    "IA_Blockchain.PrediccionDeRiesgosClinicos",
    "IA_Blockchain.GestionDeIdentidadBlockchain",
    "IA_Blockchain.VerificacionDeIntegridadDocumentos",
    "IA_Blockchain.ConfiguracionDeConsentimiento",
    # ── SeguridadAvanzadaYAdministracion ─────────────────────────────
    "SeguridadAvanzadaYAdministracion.BreakGlass_Solicitud",
    "SeguridadAvanzadaYAdministracion.BreakGlass_Aprobacion",
    "SeguridadAvanzadaYAdministracion.GestionDePermisosPaciente",
    "SeguridadAvanzadaYAdministracion.PanelDeAuditoriaYReportesSNIS",
    # ── Reportes ─────────────────────────────────────────────────────
    "SeguridadAvanzadaYAdministracion.ReporteProduccion",
    # ── Backup / Restore / Gestiones ─────────────────────────────────
    "SeguridadAvanzadaYAdministracion.BackupRestore",
    # ── Auditoría ─────────────────────────────────────────────────────
    "SeguridadAvanzadaYAdministracion.Auditoria",
    # ── Cobros ────────────────────────────────────────────────────────
    "GestionDeCobros",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Multitenant — debe ir después de AuthenticationMiddleware
    "Tenants.middleware.TenantMiddleware",
    "SeguridadAvanzadaYAdministracion.Auditoria.middleware.AuditMiddleware",
]

ROOT_URLCONF = "kardex.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kardex.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # Prioriza DB_* (definidas en .env) y mantiene fallback a PG* por compatibilidad.
        "NAME": config("DB_NAME", default=os.environ.get("PGDATABASE", "histolink")),
        "USER": config("DB_USER", default=os.environ.get("PGUSER", "postgres")),
        "PASSWORD": config("DB_PASSWORD", default=os.environ.get("PGPASSWORD", "Tomy2003")),
        "HOST": config("DB_HOST", default=os.environ.get("PGHOST", "localhost")),
        "PORT": config("DB_PORT", default=os.environ.get("PGPORT", "5432")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Archivos subidos (resultados de estudios T009 / adjuntos)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── CACHÉ — Redis DB0 default; DB1 especialidades (T009); DB2 rate limit; DB3 antecedentes
# Si REDIS_URL está definido (producción), las rutas usan ese host/puerto base.
_REDIS_URL = os.environ.get("REDIS_URL", "")
# ── CACHÉ — Redis con fallback a memoria ─────────────────────────────────────
# Si REDIS_URL está definido (producción) usa Redis; si no, usa memoria local.
_REDIS_URL = config("REDIS_URL", default="")
if _REDIS_URL:
    _base = _REDIS_URL.rstrip("/")
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"{_base}/0",
        },
        "antecedentes": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"{_base}/3",
            "TIMEOUT": 900,
        },
        "rate_limit": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"{_base}/2",
        },
        "especialidad_cache": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"{_base}/1",
            "TIMEOUT": 3600,
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
        "antecedentes": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "TIMEOUT": 900,
        },
        "rate_limit": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
        "especialidad_cache": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "TIMEOUT": 3600,
        },
    }

# ── LOGGING — Auditoría ───────────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "auditoria": {
            "format": (
                "%(asctime)s [AUDITORIA] user=%(user)s method=%(method)s "
                "path=%(path)s status=%(status)s dur=%(duracion_ms)sms body=%(body)s"
            ),
        },
        "simple": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "auditoria_console": {
            "class": "logging.StreamHandler",
            "formatter": "auditoria",
        },
    },
    "loggers": {
        "histolink.auditoria": {
            "handlers": ["auditoria_console"],
            "level": "INFO",
            "propagate": False,
        },
        "histolink.antecedentes": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# DRF configurations
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Histolink API",
    "DESCRIPTION": "Documentacion automatica de la API del sistema clinico Histolink.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

# CORS
CORS_ALLOW_ALL_ORIGINS = _env_bool(
    config("CORS_ALLOW_ALL_ORIGINS", default="True"),
    default=True,
)

# ── Email / SMTP (Gmail) ─────────────────────────────────────────────────
# Configura EMAIL_HOST_USER y EMAIL_HOST_PASSWORD en el archivo .env
# Para Gmail: genera una "Contraseña de aplicación" en myaccount.google.com
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default='True', cast=lambda v: v.strip().lower() in ('true', '1', 'yes'))
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Histolink <no-reply@histolink.com>')

# Simple JWT configurations for secure, long-lived tokens
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # Short access token for security
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),    # Long refresh token
    "ROTATE_REFRESH_TOKENS": True,                   # Re-issue a new refresh token on use
    "BLACKLIST_AFTER_ROTATION": True,                # Blacklist old refresh tokens
    "UPDATE_LAST_LOGIN": True,
    
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}
