"""
Django settings for Histolink project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # ── GestionDeUsuarios ─────────────────────────────────────────────
    "GestionDeUsuarios.LoginYAutenticacion",
    "GestionDeUsuarios.GestionDePersonalDeSalud",
    "GestionDeUsuarios.RegistroYBusquedaDePacientes",
    "GestionDeUsuarios.VisualizacionDelExpediente",
    "GestionDeUsuarios.EdicionDeAntecedentesMedicos",
    # ── AtencionClinica ───────────────────────────────────────────────
    "AtencionClinica.AperturaFichaYColaDeAtencion",
    "AtencionClinica.RegistroDeTriaje",
    "AtencionClinica.ConsultaMedicaSOAP",
    "AtencionClinica.EmisionDeRecetaMedica",
    "AtencionClinica.SolicitudDeEstudios",
    "AtencionClinica.FirmaDigitalDeConsulta",
    # ── IA_Blockchain ─────────────────────────────────────────────────
    "IA_Blockchain.ClasificacionDeUrgenciaConIA",
    "IA_Blockchain.PrediccionDeRiesgosClinicos",
    "IA_Blockchain.GestionDeIdentidadBlockchain",
    "IA_Blockchain.VerificacionDeIntegridadDocumentos",
    "IA_Blockchain.ConfiguracionDeConsentimiento",
    # ── SeguridadAvanzadaYAdministracion ─────────────────────────────
    "SeguridadAvanzadaYAdministracion.BreakGlass_Solicitud",
    "SeguridadAvanzadaYAdministracion.BreakGlass_Aprobacion",
    "SeguridadAvanzadaYAdministracion.GestionDePermisosPaciente",
    "SeguridadAvanzadaYAdministracion.PanelDeAuditoriaYReportesSNIS",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # T008 — Auditoría de operaciones de escritura
    "kardex.middleware.AuditoriaMiddleware",
]

ROOT_URLCONF = "kardex.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kardex.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="histolink"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── CACHÉ — Redis ────────────────────────────────────────────────────────────
# DB0: reservado para uso general / sesiones
# DB1: antecedentes médicos (T008)
_REDIS_URL = config("REDIS_URL", default="redis://127.0.0.1:6379")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"{_REDIS_URL}/0",
    },
    "antecedentes": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"{_REDIS_URL}/1",
        "TIMEOUT": 900,
    },
}

# ── LOGGING — Auditoría ───────────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "auditoria": {
            "format": (
                "%(asctime)s [AUDITORIA] user=%(user)s method=%(method)s "
                "path=%(path)s status=%(status)s dur=%(duracion_ms)sms body=%(body)s"
            ),
        },
        "simple": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "auditoria_console": {
            "class": "logging.StreamHandler",
            "formatter": "auditoria",
        },
    },
    "loggers": {
        # Auditoría de escrituras (middleware T008)
        "histolink.auditoria": {
            "handlers": ["auditoria_console"],
            "level": "INFO",
            "propagate": False,
        },
        # Logger interno de la app antecedentes
        "histolink.antecedentes": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# DRF configurations
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# CORS
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)

# Simple JWT configurations for secure, long-lived tokens
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # Short access token for security
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),    # Long refresh token
    "ROTATE_REFRESH_TOKENS": True,                   # Re-issue a new refresh token on use
    "BLACKLIST_AFTER_ROTATION": True,                # Blacklist old refresh tokens
    "UPDATE_LAST_LOGIN": True,
    
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}
