# Generated by Django 5.1.4 on 2026-05-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('hash_previo', models.CharField(blank=True, default='', max_length=64)),
                ('hash_actual', models.CharField(db_index=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento Blockchain',
                'verbose_name_plural': 'Eventos Blockchain',
                'ordering': ['-creado_en'],
            },
        ),
    ]
