<<<<<<< HEAD
# Generated by Django 5.1.4 on 2026-05-24 20:58

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.1.4 on 2026-05-17 02:56

>>>>>>> origin/alejandra
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Tenants', '0002_configuraciontenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> origin/alejandra
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('numero_bloque', models.PositiveIntegerField()),
                ('anterior_hash', models.CharField(max_length=64)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('documento_tipo', models.CharField(max_length=50)),
                ('documento_id', models.PositiveIntegerField()),
                ('hash_documento', models.CharField(max_length=64)),
                ('firma_rsa', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bloque_hash', models.CharField(max_length=64)),
                ('firmado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_blockchain', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_blockchain', to='Tenants.tenant')),
            ],
            options={
                'ordering': ['numero_bloque'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='IdentidadBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_publica_pem', models.TextField()),
                ('clave_privada_pem', models.TextField()),
                ('did_simulado', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identidades_blockchain', to='Tenants.tenant')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identidad_blockchain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
=======
                ('tipo_evento', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('hash_previo', models.CharField(blank=True, default='', max_length=64)),
                ('hash_actual', models.CharField(db_index=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento Blockchain',
                'verbose_name_plural': 'Eventos Blockchain',
                'ordering': ['-creado_en'],
            },
        ),
>>>>>>> origin/alejandra
    ]
