# Generated by Django 5.1.4 on 2026-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeIdentidadBlockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoblockchain',
            name='timestamp_bloque',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
