# Generated by Django 5.1.4 on 2026-06-17 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AperturaFichaYColaDeAtencion', '0003_merge_20260503_2250'),
        ('RegistroYBusquedaDePacientes', '0005_merge_20260424_0726'),
        ('Tenants', '0002_configuraciontenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='AperturaFichaYColaDeAtencion.ficha')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='RegistroYBusquedaDePacientes.paciente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='Tenants.tenant')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
