# Generated by Django 5.1.4 on 2026-05-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tenants', '0002_configuraciontenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('congelada', models.BooleanField(default=False, help_text='Si está congelada, los datos de este año son de solo lectura.', verbose_name='Congelada')),
                ('fecha_congelamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de congelamiento')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Nota opcional sobre esta gestión.', max_length=200, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='Tenants.tenant', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Gestión anual',
                'verbose_name_plural': 'Gestiones anuales',
                'ordering': ['-año'],
                'unique_together': {('tenant', 'año')},
            },
        ),
    ]
