# Generated by Django 5.1.4 on 2026-04-04 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConsultaMedicaSOAP', '0001_initial'),
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('firmada', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='ConsultaMedicaSOAP.consultasoap')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='RegistroYBusquedaDePacientes.paciente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('indicaciones', models.TextField(blank=True, default='')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EmisionDeRecetaMedica.receta')),
            ],
            options={
                'verbose_name': 'Ítem de Receta',
                'verbose_name_plural': 'Ítems de Receta',
            },
        ),
    ]
