# Generated by Django 5.1.4 on 2026-04-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConsultaMedicaSOAP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_receta', models.CharField(db_index=True, max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('DISPENSADA', 'Dispensada'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=15)),
                ('fecha_dispensacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='ConsultaMedicaSOAP.consulta')),
                ('dispensada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recetas_dispensadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('concentracion', models.CharField(blank=True, default='', max_length=50)),
                ('forma_farmaceutica', models.CharField(blank=True, default='', max_length=50)),
                ('via_administracion', models.CharField(choices=[('VO', 'Vía oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('SC', 'Subcutánea'), ('TOP', 'Tópica'), ('INH', 'Inhalatoria'), ('SL', 'Sublingual'), ('REC', 'Rectal'), ('OFT', 'Oftálmica'), ('OTR', 'Otra')], default='VO', max_length=5)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('cantidad_total', models.CharField(blank=True, default='', max_length=50)),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='EmisionDeRecetaMedica.receta')),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
                'ordering': ['orden'],
            },
        ),
    ]
