# Generated by Django 5.1.4 on 2026-04-05 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaMedicaSOAP', '0002_alter_consulta_actualizado_en_and_more'),
        ('EmisionDeRecetaMedica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallereceta',
            name='cantidad_total',
            field=models.CharField(blank=True, default='', help_text='Total que debe entregar farmacia. Ej: 21 tabletas, 1 frasco de 120ml.', max_length=50, verbose_name='Cantidad total a dispensar'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='concentracion',
            field=models.CharField(blank=True, default='', help_text='Concentración del medicamento. Ej: 500mg, 250mg/5ml, 10mg/ml.', max_length=50, verbose_name='Concentración'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='dosis',
            field=models.CharField(help_text='Cantidad a administrar por toma. Ej: 1 tableta, 5ml, 500mg.', max_length=100, verbose_name='Dosis'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='duracion',
            field=models.CharField(help_text='Por cuánto tiempo. Ej: 7 días, 1 mes, hasta terminar.', max_length=100, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='forma_farmaceutica',
            field=models.CharField(blank=True, default='', help_text='Presentación del medicamento. Ej: tableta, jarabe, ampolla, crema, parche.', max_length=50, verbose_name='Forma farmacéutica'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='frecuencia',
            field=models.CharField(help_text='Cada cuánto se toma. Ej: cada 8 horas, 3 veces al día, una vez al día.', max_length=100, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='instrucciones',
            field=models.TextField(blank=True, default='', help_text='Indicaciones adicionales para el paciente. Ej: tomar con alimentos, evitar el sol.', verbose_name='Instrucciones especiales'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='medicamento',
            field=models.CharField(help_text='Nombre genérico DCI del medicamento. Ej: Amoxicilina, Ibuprofeno. No usar marcas comerciales.', max_length=200, verbose_name='Medicamento'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1, help_text='Posición del medicamento en la receta impresa. 1 = primero, 2 = segundo, etc.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='receta',
            field=models.ForeignKey(help_text='Receta a la que pertenece este medicamento.', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='EmisionDeRecetaMedica.receta', verbose_name='Receta'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='via_administracion',
            field=models.CharField(choices=[('VO', 'Vía oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('SC', 'Subcutánea'), ('TOP', 'Tópica'), ('INH', 'Inhalatoria'), ('SL', 'Sublingual'), ('REC', 'Rectal'), ('OFT', 'Oftálmica'), ('OTR', 'Otra')], default='VO', help_text='Ruta por la que se administra el medicamento. VO = vía oral (más común).', max_length=5, verbose_name='Vía de administración'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='consulta',
            field=models.ForeignKey(help_text='Consulta médica en la que se emitió esta receta.', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='ConsultaMedicaSOAP.consulta', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dispensada_por',
            field=models.ForeignKey(blank=True, help_text='Personal de farmacia que dispensó la receta. Nulo hasta que se dispense.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recetas_dispensadas', to=settings.AUTH_USER_MODEL, verbose_name='Dispensada por'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='estado',
            field=models.CharField(choices=[('EMITIDA', 'Emitida'), ('DISPENSADA', 'Dispensada'), ('ANULADA', 'Anulada')], default='EMITIDA', help_text='Estado de la receta: EMITIDA (pendiente de dispensar), DISPENSADA (entregada en farmacia), ANULADA.', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_dispensacion',
            field=models.DateTimeField(blank=True, help_text='Timestamp de cuándo fue dispensada en farmacia.', null=True, verbose_name='Fecha de dispensación'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de cuándo fue emitida la receta.', verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='medico',
            field=models.ForeignKey(help_text='Médico que emitió la receta.', on_delete=django.db.models.deletion.PROTECT, related_name='recetas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='numero_receta',
            field=models.CharField(db_index=True, help_text='Correlativo único generado automáticamente. Ej: REC-2026-00123.', max_length=20, unique=True, verbose_name='Número de receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Notas adicionales del médico sobre la receta.', verbose_name='Observaciones'),
        ),
    ]
