# Generated by Django 5.1.4 on 2026-05-17 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeIdentidadBlockchain', '0001_initial'),
        ('RegistroYBusquedaDePacientes', '0005_merge_20260424_0726'),
        ('Tenants', '0002_configuraciontenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakGlassSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField()),
                ('nivel_urgencia', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('acceso_desde', models.DateTimeField(blank=True, null=True)),
                ('acceso_hasta', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='break_glass_aprobaciones', to=settings.AUTH_USER_MODEL)),
                ('evento_blockchain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_glass_solicitudes', to='GestionDeIdentidadBlockchain.eventoblockchain')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_glass_solicitudes', to='RegistroYBusquedaDePacientes.paciente')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_glass_solicitudes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_solicitudes', to='Tenants.tenant')),
            ],
            options={
                'verbose_name': 'Solicitud Break-Glass',
                'verbose_name_plural': 'Solicitudes Break-Glass',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['solicitante', 'paciente', 'estado'], name='bg_sol_pac_est_idx'), models.Index(fields=['acceso_hasta'], name='bg_acc_hasta_idx')],
            },
        ),
    ]
