# Generated by Codex for CU17 Break-Glass approval/rejection

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakGlass_Solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakglasssolicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
