# Generated by Django 5.1.4 on 2026-04-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedades_cronicas', models.TextField(blank=True, default='')),
                ('cirugias_previas', models.TextField(blank=True, default='')),
                ('hospitalizaciones', models.TextField(blank=True, default='')),
                ('alergias', models.TextField(blank=True, default='')),
                ('medicacion_actual', models.TextField(blank=True, default='')),
                ('vacunas', models.TextField(blank=True, default='')),
                ('antecedentes_familiares', models.TextField(blank=True, default='')),
                ('fuma', models.BooleanField(default=False)),
                ('consume_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='RegistroYBusquedaDePacientes.paciente')),
            ],
            options={
                'verbose_name': 'Antecedentes Médicos',
                'verbose_name_plural': 'Antecedentes Médicos',
            },
        ),
    ]
