# Generated by Django 5.1.4 on 2026-04-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('?', 'Desconocido')], default='?', max_length=3)),
                ('alergias', models.TextField(blank=True, default='')),
                ('ant_patologicos', models.TextField(blank=True, default='', verbose_name='Antecedentes patológicos')),
                ('ant_no_patologicos', models.TextField(blank=True, default='', verbose_name='Antecedentes no patológicos')),
                ('ant_quirurgicos', models.TextField(blank=True, default='', verbose_name='Antecedentes quirúrgicos')),
                ('ant_familiares', models.TextField(blank=True, default='', verbose_name='Antecedentes familiares')),
                ('ant_gineco_obstetricos', models.TextField(blank=True, default='', verbose_name='Antecedentes gineco-obstétricos')),
                ('medicacion_actual', models.TextField(blank=True, default='')),
                ('esquema_vacunacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='RegistroYBusquedaDePacientes.paciente')),
                ('ultima_actualizacion_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
    ]
