# Generated by Django 5.1.4 on 2026-04-05 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdicionDeAntecedentesMedicos', '0001_initial'),
        ('RegistroYBusquedaDePacientes', '0002_alter_paciente_activo_alter_paciente_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación.', verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='alergias',
            field=models.TextField(blank=True, default='', help_text='Lista de alergias conocidas. Ej: Penicilina, látex, maní. Una por línea.', verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='ant_familiares',
            field=models.TextField(blank=True, default='', help_text='Enfermedades hereditarias o de alta incidencia familiar. Ej: Diabetes en padre y abuelo.', verbose_name='Antecedentes familiares'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='ant_gineco_obstetricos',
            field=models.TextField(blank=True, default='', help_text='Solo para pacientes femeninas. Formato G:P:A:C (Gestas:Partos:Abortos:Cesáreas). Ej: G3P2A1C0.', verbose_name='Antecedentes gineco-obstétricos'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='ant_no_patologicos',
            field=models.TextField(blank=True, default='', help_text='Hábitos y estilo de vida. Ej: tabaquismo 10 cig/día, consumo ocasional de alcohol.', verbose_name='Antecedentes no patológicos'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='ant_patologicos',
            field=models.TextField(blank=True, default='', help_text='Enfermedades crónicas actuales del paciente. Ej: Diabetes tipo 2, HTA.', verbose_name='Antecedentes patológicos'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='ant_quirurgicos',
            field=models.TextField(blank=True, default='', help_text='Cirugías previas con fecha aproximada. Ej: Apendicectomía 2018.', verbose_name='Antecedentes quirúrgicos'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación.', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='esquema_vacunacion',
            field=models.TextField(blank=True, default='', help_text='Vacunas aplicadas y fechas. Ej: Hepatitis B (2020), Influenza (2024).', verbose_name='Esquema de vacunación'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('?', 'Desconocido')], default='?', help_text="Grupo sanguíneo del paciente. Usar '?' si se desconoce.", max_length=3, verbose_name='Grupo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='medicacion_actual',
            field=models.TextField(blank=True, default='', help_text='Medicamentos crónicos permanentes que toma el paciente. No incluir los de cada consulta.', verbose_name='Medicación actual'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='paciente',
            field=models.OneToOneField(help_text='Paciente al que pertenece este historial. Relación uno a uno.', on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='RegistroYBusquedaDePacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='ultima_actualizacion_por',
            field=models.ForeignKey(blank=True, help_text='Personal de salud que realizó la última modificación de este historial.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Última actualización por'),
        ),
    ]
