# Generated by Django 5.1.4 on 2026-04-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDePersonalDeSalud', '0002_alter_especialidad_nombre'),
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='Tenants.tenant', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='personalsalud',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_salud', to='Tenants.tenant', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='item_min_salud',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='especialidad',
            unique_together={('nombre', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='personalsalud',
            unique_together={('item_min_salud', 'tenant')},
        ),
    ]
