# Generated by Django 5.1.4 on 2026-04-04 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroDeTriaje', '0001_initial'),
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaSOAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subjetivo', models.TextField(verbose_name='Subjetivo (síntomas referidos por el paciente)')),
                ('objetivo', models.TextField(verbose_name='Objetivo (hallazgos del examen físico)')),
                ('analisis', models.TextField(verbose_name='Análisis / Diagnóstico')),
                ('plan', models.TextField(verbose_name='Plan de tratamiento')),
                ('diagnostico_cie10', models.CharField(blank=True, default='', max_length=10, verbose_name='Código CIE-10')),
                ('diagnostico_descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='RegistroYBusquedaDePacientes.paciente')),
                ('triaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='RegistroDeTriaje.triaje')),
            ],
            options={
                'verbose_name': 'Consulta SOAP',
                'verbose_name_plural': 'Consultas SOAP',
                'ordering': ['-fecha'],
            },
        ),
    ]
