# Generated by Django 5.1.4 on 2026-04-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroDeTriaje', '0001_initial'),
        ('RegistroYBusquedaDePacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADA', 'Completada'), ('FIRMADA', 'Firmada')], default='BORRADOR', max_length=15)),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('historia_enfermedad_actual', models.TextField(verbose_name='Historia de la enfermedad actual')),
                ('examen_fisico', models.TextField(blank=True, default='', verbose_name='Examen físico')),
                ('impresion_diagnostica', models.TextField(verbose_name='Impresión diagnóstica')),
                ('codigo_cie10_principal', models.CharField(db_index=True, max_length=10, verbose_name='Código CIE-10 principal')),
                ('codigo_cie10_secundario', models.CharField(blank=True, default='', max_length=10)),
                ('descripcion_cie10', models.CharField(blank=True, default='', max_length=300)),
                ('plan_tratamiento', models.TextField(blank=True, default='', verbose_name='Plan de tratamiento')),
                ('indicaciones_alta', models.TextField(blank=True, default='', verbose_name='Indicaciones al alta')),
                ('requiere_derivacion', models.BooleanField(default=False)),
                ('derivacion_destino', models.CharField(blank=True, default='', max_length=200)),
                ('derivacion_motivo', models.TextField(blank=True, default='')),
                ('hash_documento', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('firmada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('firmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas_firmadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='RegistroYBusquedaDePacientes.paciente')),
                ('triaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='RegistroDeTriaje.triaje')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['medico', 'creado_en'], name='idx_consulta_medico_fecha')],
            },
        ),
    ]
