# Generated by Django 5.1.4 on 2026-04-05 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaMedicaSOAP', '0001_initial'),
        ('RegistroDeTriaje', '0002_alter_triaje_enfermera_alter_triaje_escala_dolor_and_more'),
        ('RegistroYBusquedaDePacientes', '0002_alter_paciente_activo_alter_paciente_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación.', verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigo_cie10_principal',
            field=models.CharField(db_index=True, help_text='OBLIGATORIO para estadísticas SNIS Bolivia. Ej: J18.9 (Neumonía), E11 (Diabetes tipo 2).', max_length=10, verbose_name='Código CIE-10 principal'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigo_cie10_secundario',
            field=models.CharField(blank=True, default='', help_text='Diagnóstico secundario: complicación o comorbilidad relevante. Opcional.', max_length=10, verbose_name='Código CIE-10 secundario'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación de la consulta.', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='derivacion_destino',
            field=models.CharField(blank=True, default='', help_text='Establecimiento o especialidad a donde se deriva. Ej: Hospital de 2do nivel, Cardiología.', max_length=200, verbose_name='Destino de derivación'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='derivacion_motivo',
            field=models.TextField(blank=True, default='', help_text='Justificación clínica de por qué se deriva al paciente.', verbose_name='Motivo de derivación'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='descripcion_cie10',
            field=models.CharField(blank=True, default='', help_text='Descripción textual del código CIE-10 principal para lectura rápida.', max_length=300, verbose_name='Descripción del diagnóstico CIE-10'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADA', 'Completada'), ('FIRMADA', 'Firmada')], default='BORRADOR', help_text='Ciclo de vida: BORRADOR (en edición) → COMPLETADA (lista) → FIRMADA (con firma digital).', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='examen_fisico',
            field=models.TextField(blank=True, default='', help_text='SOAP-O: Hallazgos del examen físico por sistemas. Ej: Abdomen: dolor en FID a la palpación.', verbose_name='Examen físico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='firmada_en',
            field=models.DateTimeField(blank=True, help_text='Timestamp de cuándo se realizó la firma digital.', null=True, verbose_name='Firmada en'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='firmada_por',
            field=models.ForeignKey(blank=True, help_text='Médico que firmó digitalmente la consulta. Nulo hasta que se firme.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas_firmadas', to=settings.AUTH_USER_MODEL, verbose_name='Firmada por'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hash_documento',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 del contenido de la consulta. Vacío hasta que el médico firma. Se ancla en blockchain.', max_length=64, verbose_name='Hash del documento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='historia_enfermedad_actual',
            field=models.TextField(help_text='SOAP-S: Relato cronológico de inicio, evolución, síntomas asociados y factores modificadores.', verbose_name='Historia de la enfermedad actual'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='impresion_diagnostica',
            field=models.TextField(help_text='SOAP-A: Diagnóstico presuntivo o definitivo del médico.', verbose_name='Impresión diagnóstica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='indicaciones_alta',
            field=models.TextField(blank=True, default='', help_text='Instrucciones entregadas al paciente al momento de salir del establecimiento.', verbose_name='Indicaciones al alta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(help_text='Médico que realizó la consulta.', on_delete=django.db.models.deletion.PROTECT, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.TextField(help_text="SOAP-S: Por qué viene el paciente. En sus propias palabras. Ej: 'Dolor abdominal de 3 días'.", verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente atendido en esta consulta.', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='RegistroYBusquedaDePacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='plan_tratamiento',
            field=models.TextField(blank=True, default='', help_text='SOAP-P: Indicaciones, tratamiento no farmacológico, seguimiento y controles.', verbose_name='Plan de tratamiento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='requiere_derivacion',
            field=models.BooleanField(default=False, help_text='True si el paciente necesita ser atendido en otro nivel de atención.', verbose_name='Requiere derivación'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='triaje',
            field=models.OneToOneField(blank=True, help_text='Triaje previo asociado a esta consulta. Opcional si no pasó por triaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='RegistroDeTriaje.triaje', verbose_name='Triaje'),
        ),
    ]
