# Generated by Django 5.1.4 on 2026-04-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaMedicaSOAP', '0002_alter_consulta_actualizado_en_and_more'),
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='Tenants.tenant', verbose_name='Establecimiento'),
        ),
    ]
