# Generated by Django 5.1.4 on 2026-05-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaMedicaSOAP', '0003_consulta_tenant'),
        ('ConsultaMedicaSOAP', '0005_remove_consulta_paciente_ficha_not_null'),
    ]

    operations = [
    ]
