# Generated by Django 5.1.4 on 2026-05-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaMedicaSOAP', '0007_alter_consulta_codigo_cie10_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='codigo_cie10_principal',
            field=models.CharField(db_index=True, help_text='OBLIGATORIO para estadísticas SNIS Bolivia. Ej: J18.9 (Neumonía), E11 (Diabetes tipo 2).', max_length=10, verbose_name='Código CIE-10 principal'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='historia_enfermedad_actual',
            field=models.TextField(help_text='SOAP-S: Relato cronológico de inicio, evolución, síntomas asociados y factores modificadores.', verbose_name='Historia de la enfermedad actual'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='impresion_diagnostica',
            field=models.TextField(help_text='SOAP-A: Diagnóstico presuntivo o definitivo del médico.', verbose_name='Impresión diagnóstica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.TextField(help_text="SOAP-S: Por qué viene el paciente. En sus propias palabras. Ej: 'Dolor abdominal de 3 días'.", verbose_name='Motivo de consulta'),
        ),
    ]
